language: python
python:
  - "2.7"

dist: trusty

before_install:
  - echo $TRAVIS_OS_NAME

install:
  #- sudo apt-get update
  - wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
  - ./bin/micromamba shell init -s bash -p $HOME/micromamba
  - micromamba create -y -n testenv python=$TRAVIS_PYTHON_VERSION -c conda-forge -c mantid -c mantid/label/nightly
  - micromamba activate testenv
  - micromamba install -y pylint matplotlib numpy pyqt=5 mantid-framework=4.0
  - pip install --upgrade codecov
  - cd test
  - wget http://198.74.56.37/ftp/external-data/MD5/214df921d4fa70ff5a33c4eb6f8284ad -O REF_M_24949
  - wget http://198.74.56.37/ftp/external-data/MD5/58d6698e1d6bf98e0315687cb980d333 -O REF_M_29160

script:
  #- python setup.py install
  - cd test; coverage run data_handling_test.py

after_success:
  - codecov
