name: quicknxs
channels:
    - conda-forge
    - mantid/label/nightly
    - mantid
dependencies:
- matplotlib
- numpy
- mantid>=6.3,<6.4
- pytest
- pytest-qt
- build
- toml
- pip:
    - versioningit
    - check-wheel-contents