name: quicknxs
channels:
    - conda-forge
    - mantid
dependencies:
- matplotlib
- mantid>=6.3,<6.4
- codecov
- conda-build
- conda-verify
- pylint
- pytest
- pytest-qt
- pytest-cov
- build
- toml
- pip:
    - versioningit
    - check-wheel-contents
