name: gui
channels:
    - conda-forge
    - mantid/label/nightly
    - mantid
    - anaconda
dependencies:
- cycler
- freetype
- libpng
- matplotlib
- mkl
- numpy=
- openssl
- pip
- pyparsing
- pyqt>=5.12.3,<6
- python=3.8.*
- python-dateutil
- pytz
- qt>=5.12.9,<6
- qtpy>=1.9.0
- readline
- setuptools
- sip
- six
- sqlite
- tk
- wheel
- zlib
- pillow
- scipy
- h5py>=2.10.0,<3
- hdf5=1.10.*
- mantid>=6.3,<6.4

