name: test-code-cov

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        mamba-version: "*"
        environment-file: environment.yml
    - name: Unit test with code coverage
      run: xvfb-run -a python -m pytest -vv --cov=reflectivity_ui --cov-report=xml --cov-report=term test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
