name: unit-test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        mamba-version: "*"
        environment-file: environment.yml
    - name: Install quicknxs via setup.py
      run: python setup.py install
    - name: Build Wheel
      run: python -m build --no-isolation --wheel
    - name: Check Wheel Contents
      run: check-wheel-contents .
